export const CREATE_COMMITE_REQUEST="CREATE_COMMITE_REQUEST";
export const CREATE_COMMITE_SUCCESS="CREATE_COMMITE_SUCCESS";
export const CREATE_COMMITE_FAIL="CREATE_COMMITE_FAIL";

export const FETCH_COMMITE_REQUEST="FETCH_COMMITE_REQUEST";
export const FETCH_COMMITE_SUCCESS="FETCH_COMMITE_SUCCESS";
export const FETCH_COMMITE_FAIL="FETCH_COMMITE_FAIL";


export const FETCH_COMMITE_INFO_REQUEST="FETCH_COMMITE_REQUEST";
export const FETCH_COMMITE_SUCCESS="FETCH_COMMITE_SUCCESS";
export const FETCH_COMMITE_FAIL="FETCH_COMMITE_FAIL";
