export const CREATE_PATIENT_REQUEST="CREATE_PATIENT_REQUEST";
export const CREATE_PATIENT_SUCCESS="CREATE_PATIENT_SUCCESS";
export const CREATE_PATIENT_FAIL="CREATE_PATIENT_FAIL";

export const FETCH_PATIENT_REQUEST="FETCH_PATIENT_REQUEST";
export const FETCH_PATIENT_SUCCESS="FETCH_PATIENT_SUCCESS";
export const FETCH_PATIENT_FAIL="FETCH_PATIENT_FAIL";

